version: '3.8'
services:
  lua_server:
    image: openresty
    volumes:
      - ./SERVER:/app   # Ensure the SERVER directory is correctly mapped
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
